### ISSUE TITLE
Canonicalization?

### ISSUE THREAD

**Issue by quartzjer** [quartzjer/did-jwk#7]
@[kdenhartog](https://github.com/w3c/did-spec-registries/pull/432#pullrequestreview-937058461)
> Out of curiosity why not run it through the JCS algorithm first before converting it to a UTF-8 string?

I did consider this route, but decided that I wanted to keep the requirements extremely minimal.

The intent is for the owner to maintain these DIDs in their serialized form as the default/simplest use-case.  They MAY decide to store in some other form and canonicalize, but that isn't required by the method.

**Comment by kdenhartog** [comment]
Ok makes sense - the main reason I asked is because the shifting of the identifier is going to create a new point of differentiation for other methods that will (if history repeats itself) be architected around I'd expect. I see no problems with this design choice but I fully suspect someone will not like it and try to design around it. I'm good with closing this as is and this issue being a point of historical documentation for the design choice.

**Comment by quartzjer** [comment]
Yep, good thread, thanks @kdenhartog!
